#!/bin/bash
###
# Script for doing an initial build of the jessene godot lua module.
# Mostly intended for use in travis.
###

# #
# name and print provided arguments
# #
LUA_VERSION="$1"
JOBS="$2"

echo ""
echo "LUA_VERSION: $LUA_VERSION"
echo "JOBS: $JOBS"
echo ""

# #
# validations
# #

# make sure the current directory is correct
if [[ ! "$PWD" =~ "/jessene/scripts" ]]; then
  echo "Not in scripts directory, current directory is $PWD, exiting..."
  exit 1
fi

# check that the needed arguments were provided
if [ "$LUA_VERSION" = "" ]; then
  echo "LUA_VERSION(first argument) not provided, exiting..."
  exit 1
fi

if [ "$JOBS" = "" ]; then
  echo "JOBS(second argument) not provided, exiting..."
  exit 1
fi

# #
# download and compile lua
# #

# go from */jessene/scripts to */jessene
cd ..
# download and decompress lua source code
wget https://www.lua.org/ftp/lua-"$LUA_VERSION".tar.gz || { echo "Failed to download lua $LUA_VERSION source! Exiting..."; exit 1; }
tar -xvzf lua-"$LUA_VERSION".tar.gz
rm lua-"$LUA_VERSION".tar.gz
# softlink directly to lua's src/ directory and compile
ln -s lua-"$LUA_VERSION"/src src
cd src
make MYCFLAGS="-fPIC" linux test
cd ..

# also softlink as luasrc for below compiling
ln -s lua-"$LUA_VERSION"/src luasrc

# #
# download and compile godot-cpp
# #

# go to the directory above jessene/ and clone godot-cpp
cd ..
git clone --recursive https://github.com/GodotNativeTools/godot-cpp.git godot-cpp || { echo "Failed to clone godot-cpp! Exiting..."; exit 1; }
# compile godot-cpp as 64-bit, 32-bit requires an additional package on most systems
cd godot-cpp
scons platform=linux generate_bindings=yes bits=64 -j $JOBS || { echo "Building godot-cpp failed!"; exit 1; }
cd ..

# #
# compile jessene
# #

# create containing directory for the lua module
mkdir Godot-Lua-Library
mkdir Godot-Lua-Library/bin
mkdir Godot-Lua-Library/src

# softlink to jessene
cd Godot-Lua-Library/src
ln -s ../../jessene jessene

# softlink to godot-cpp and jessene's SConstruct
cd ..
ln -s ../godot-cpp godot-cpp
ln -s src/jessene/SConstruct SConstruct

# build jessene
scons platform=linux bits=64

